Document: gw6c
Title: Debian gw6c Manual
Author: <insert document author here>
Abstract: This manual describes what gw6c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gw6c/gw6c.sgml.gz

Format: postscript
Files: /usr/share/doc/gw6c/gw6c.ps.gz

Format: text
Files: /usr/share/doc/gw6c/gw6c.text.gz

Format: HTML
Index: /usr/share/doc/gw6c/html/index.html
Files: /usr/share/doc/gw6c/html/*.html
